public enum Fase {
    ATTESA,
    PREPARAZIONE_ROSSO,
    TIRO_VERDE_GIALLO,
    SCONTRO_TIRO_SX,
    SCONTRO_TIRO_DX,
    EMERGENZA,
    RECUPERO_ATTESA,
    RECUPERO_TIRO,
    IDENTIFICAZIONE_MONITOR
}
